name: Test and Deploy Lib

on:
  push:
    branches:
      - main
      - master 

permissions:
  contents: read
  packages: write 

jobs: 
  test-lib:
    name: 🧪 Test Pessoa Lib
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest

      - name: Install lib locally
        run: |
          python -m pip install ./pessoa_lib

      - name: Run tests for library
        run: |
          pytest ./pessoa_lib/tests/
  
  deploy-lib:
    name: 📦 Publish Pessoa Lib to PyPI
    runs-on: ubuntu-latest
    needs: test-lib 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build library
        run: |
          python -m build ./pessoa_lib
      
      - name: Publish library to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # Publica os arquivos de /pessoa_lib/dist/
          twine upload ./pessoa_lib/dist/*